include = ["**/Cargo.toml"]

exclude = [
  "target/**",
  "**/.cargo/registry/**",
]

[formatting]
align_comments = false
align_entries = false
array_trailing_comma = true
compact_arrays = true
compact_inline_tables = false
indent_string = "  "
reorder_arrays = false
reorder_inline_tables = false
reorder_keys = false

[[rule]]
include = ["**/Cargo.toml"]
keys = [
  "dependencies",
  "dev-dependencies",
  "build-dependencies",
  "target.*.dependencies",
  "target.*.dev-dependencies",
  "target.*.build-dependencies",
  "workspace.dependencies",
]

[rule.formatting]
reorder_keys = true
