[package]
name = "canton"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[features]
default = ["tls-ring", "tls-webpki-roots"]
derive = ["dep:canton-types-derive", "ledger-api-value/derive"]
daml-lf = ["dep:daml-lf"]
codegen = ["dep:daml-lf-codegen"]
ledger-api = ["dep:ledger-api", "ledger-api?/v2"]
tls-ring = ["ledger-api?/tls-ring"]
tls-aws-lc = ["ledger-api?/tls-aws-lc"]
tls-native-roots = ["ledger-api?/tls-native-roots"]
tls-webpki-roots = ["ledger-api?/tls-webpki-roots"]
dpm-build = ["dep:dpm-build"]
full = [
  "derive",
  "daml-lf",
  "codegen",
  "ledger-api",
  "tls-ring",
  "tls-webpki-roots",
  "dpm-build",
]

[dependencies]
canton-types = { workspace = true, default-features = true }
canton-types-derive = { workspace = true, optional = true }
daml-lf = { workspace = true, default-features = true, optional = true }
daml-lf-codegen = { workspace = true, default-features = true, optional = true }
dpm-build = { workspace = true, default-features = true, optional = true }
ledger-api = { workspace = true, default-features = false, optional = true }
ledger-api-types = { workspace = true, default-features = true }
ledger-api-value = { workspace = true, default-features = true }
