[package]
name = "canton-paths"
version = "0.1.0"
description = "Canton Rust paths definitions"
edition.workspace = true
license.workspace = true

[features]
default = []

# Enables Debug, PartialEq, Eq impls on Paths type
extra = ["syn/extra-traits"]

[dependencies]
syn = { workspace = true, features = [
  "parsing",
  "printing",
  "derive",
  "clone-impls",
] }

[dev-dependencies]
canton = { workspace = true, features = ["ledger-api"] }
prettyplease.workspace = true
tempfile.workspace = true
trybuild.workspace = true
