# This workflow is managed by gh actions-lock.

name: Rust Checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.4.0
      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          default: true
          components: rustfmt
      - name: Use Rust cache
        uses: Swatinem/rust-cache@v2.9.2
      - name: Check formatting
        run: cargo fmt --check --all --verbose

  lint:
    name: Run linting
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.4.0
      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          default: true
          components: clippy
      - name: Install Protoc
        uses: arduino/setup-protoc@v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Rust cache
        uses: Swatinem/rust-cache@v2.9.2
      - name: Run linting
        run: |
          cargo clippy --no-deps --all-targets --all-features --workspace --verbose -- --deny warnings

  check-build:
    name: Check build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.4.0
      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          default: true
      - name: Install Protoc
        uses: arduino/setup-protoc@v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Rust cache
        uses: Swatinem/rust-cache@v2.9.2
      - name: Run build check
        run: |
          cargo check --workspace --all-targets --all-features --verbose

  build-docs:
    name: Build docs
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.4.0
      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          default: true
      - name: Install Protoc
        uses: arduino/setup-protoc@v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Rust cache
        uses: Swatinem/rust-cache@v2.9.2
      - name: Build docs
        env:
          RUSTDOCFLAGS: "-D warnings"
        run: cargo doc --workspace --all-features --no-deps --verbose

  run-tests:
    name: Run tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.4.0
      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          default: true
      - name: Install Protoc
        uses: arduino/setup-protoc@v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Rust cache
        uses: Swatinem/rust-cache@v2.9.2
      - name: Run tests
        run: |
          cargo test --workspace --all-features --verbose

  check-toml-format:
    name: Run Toml Format
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.4.0

      - uses: uncenter/setup-taplo@v1.0.8
        with:
          version: "0.9.3"

      - name: taplo fmt check
        shell: bash
        run: |
          taplo fmt --check
          taplo check
